name: Deploy to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        sudo yarn install
        sudo yarn build
        
        # which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
        # eval $(ssh-agent -s)
        # mkdir -p ~/.ssh/
        # echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        # chmod 600 ~/.ssh/id_rsa
        # ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts

    - name: Copy build directory to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        source: "./*"
        target: ${{ secrets.TARGET }}
        
      # run: |
      #   rsync -avz --exclude='.git*' --exclude='node_modules' ./ $REMOTE_USER@$REMOTE_HOST:$TARGET

    # env:
    #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #   REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #   REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #   TARGET: ${{ secrets.TARGET }}
